services:
  - type: web
    name: internmatch-backend
    runtime: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    pythonVersion: "3.12.3"
    plan: free
    healthCheckPath: /
    envVars:
      - key: PYTHON_ENV
        value: production